[package]
name = "actor-bank"
version = "0.1.0"
edition = "2024"

[dependencies]
actix = "0.13"
actix-web = "4"
bincode = "2.0.1"
env_logger = "0.11.8"
log = "0.4.27"
rust-rocksdb = "0.41.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
